stages:
  - build
# 在docker的gitlab-runner容器中构建（发布环境）
jobdockerbuildprod:
  only:
    - master
  stage: build
  script:
    - pwd
    - node --version
    - yarn --version
    - yarn install
    - yarn build:api
    - rm -rf /home/web/*
    - cp -r packages/app-api/storybook-static/. /home/web/
    - pwd
  tags:
    - gbr-fmui-prod
stages:
  - build
# 在docker的gitlab-runner容器中构建（发布环境）
jobdockertestprod:
  only:
    - master
  stage: test
  script:
    - pwd
    - node --version
    - yarn --version
    - pwd
  tags:
    - gbr-fmui-prod
