stages:
  - build
  - test
  - deploy
# 在docker的gitlab-runner容器中构建（发布环境 -  build 构建）
prodBuild:
  only:
    - master
  stage: build
  script:
    - pwd
    - node --version
    - yarn --version
    - yarn install
    - yarn build:api
    - pwd
  tags:
    - gbr-fmui-prod
# 在docker的gitlab-runner容器中构建（发布环境 - test 测试）
prodTest1:
  only:
    - master
  stage: test
  script:
    - pwd
    - node --version
    - yarn --version
    - yarn test:api
    - pwd
  tags:
    - gbr-fmui-prod
prodTest2:
  only:
    - master
  stage: test
  script:
    - pwd
    - node --version
    - yarn --version
    - yarn test:api
    - pwd
  tags:
    - gbr-fmui-prod
# 在docker的gitlab-runner容器中构建（发布环境 - deploy 部署上线）
prodDeploy:
  only:
    - master
  stage: deploy
  script:
    - pwd
    - node --version
    - yarn --version
    - rm -rf /home/web/*
    - cp -r packages/app-api/storybook-static/. /home/web/
    - pwd
  tags:
    - gbr-fmui-prod
